### PR TITLE
Make inject_into_route async

### PR DESCRIPTION
**Pull request by zenndos**
Also keeping the synchronous version under the `SyncInjected`.

### CODE REVIEW

**Comment by danielknell** [comment]
fixes #4 :)

**Comment by matyasrichter** [comment]
@zenndos Thank you for the contribution! Would you mind adding the following test cases?
- A simple test for your new code - essentially a copy of one of the existing ones.
- A test for injecting a dependency where the provider needs access to the event loop, as a guard for regressions of the issue described in #4.

**Comment by zenndos** [comment]
> @zenndos Thank you for the contribution! Would you mind adding the following test cases?
> 
> * A simple test for your new code - essentially a copy of one of the existing ones.
> * A test for injecting a dependency where the provider needs access to the event loop, as a guard for regressions of the issue described in [Injected runs `injector.get` on a separate thread to endpoints themselves. #4](https://github.com/matyasrichter/fastapi-injector/issues/4).

Done

**Comment by matyasrichter** [comment]
Thank you @zenndos. One last thing before merging this - please run `pre-commit` on your changes. Sorry for not mentioning this in the README, I have now added a link to its documentation.

**Pull request merged**
